version: "3"
services:
  mongodb-server:
    image: mongo:3.6.8
    container_name: filmplay_mongodb
    ports:
      - 27017:27017
    volumes:
      - $HOME/docker/environment/.mongodata/filmplay:/data/db
  webapi-server:
    image: webapi:latest
    ports:
      - "8000:8000"
    depends_on:
      - mongodb-server
    environment:
      MONGODB_URI=mongodb://mongodb-server/webapi


